---
- name: Set role and inventory node taint to empty list
  set_fact:
    role_node_taints: []
    inventory_node_taints: []

- name: Node taint for nvidia GPU nodes
  set_fact:
    role_node_taints: "{{ role_node_taints + ['nvidia.com/gpu=:NoSchedule'] }}"
  when:
    - nvidia_gpu_nodes is defined
    - nvidia_accelerator_enabled | bool
    - inventory_hostname in nvidia_gpu_nodes

- name: Populate inventory node taint
  set_fact:
    inventory_node_taints: "{{ inventory_node_taints + ['%s' | format(item)] }}"
  loop: "{{ node_taints | d([]) }}"
  when:
    - node_taints is defined
    - node_taints is not string
    - node_taints is not mapping
    - node_taints is iterable
- debug:  # noqa name[missing]
    var: role_node_taints
- debug:  # noqa name[missing]
    var: inventory_node_taints

- name: Set taint to node
  command: >-
      {{ kubectl }} taint node {{ kube_override_hostname | default(inventory_hostname) }} {{ (role_node_taints + inventory_node_taints) | join(' ') }} --overwrite=true
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  changed_when: false
  when:
    - not (hosted_k8s | default(false))
    - (role_node_taints + inventory_node_taints) | length > 0

# 托管版K8s：在本地执行节点设置污点
- name: Set taint to node (Hosted K8s)
  command: >-
      {{ local_bin_dir }}/{{ kube_version }}/kubectl --kubeconfig {{ tenant_cluster_kubeconfig }} taint node {{ kube_override_hostname | default(inventory_hostname) }} {{ (role_node_taints + inventory_node_taints) | join(' ') }} --overwrite=true
  delegate_to: localhost
  changed_when: false
  when:
    - hosted_k8s | default(false)
    - tenant_cluster_kubeconfig is defined
    - (role_node_taints + inventory_node_taints) | length > 0
