"""0022

Revision ID: 0022
Revises: 0021
Create Date: 2025-08-27 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0022'
down_revision: Union[str, None] = '0021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_account_vip_info',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('account', sa.String(length=128), nullable=False, comment='账户账号'),
    sa.Column('vip', sa.String(length=128), nullable=False, comment='VIP'),
    sa.Column('metallb_ip', sa.String(length=128), nullable=False, comment='容器实例服务的Metallb IP'),
    sa.Column('create_time', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'), comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_account_vip_info_id'), 'ops_account_vip_info', ['id'], unique=False)
    op.create_index(op.f('ix_ops_account_vip_info_account'), 'ops_account_vip_info', ['account'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ops_account_vip_info_account'), table_name='ops_account_vip_info')
    op.drop_index(op.f('ix_ops_account_vip_info_id'), table_name='ops_account_vip_info')
    op.drop_table('ops_account_info')
    # ### end Alembic commands ###


